version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=TheBloke/Mistral-7B-Instruct-v0.2-GPTQ
      - MODEL_QUANTIZATION=int8
      - VECTOR_DB_BACKEND=chromadb
      - GPU_MEMORY_UTILIZATION=0.9
      - CACHE_CAPACITY=1000
      - TTL_DAYS=90
      - API_KEYS=
    volumes:
      - ./data/chroma_db:/app/data/chroma_db
      - ./data/logs:/app/data/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s